# Generated by Django 4.1.7 on 2023-03-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pynata_type', models.CharField(choices=[('Circle', 'Круглая'), ('Shield', 'Щит'), ('Figure', 'Фигурная')], max_length=50)),
                ('size_type', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=50)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(help_text='Картинка', upload_to='card/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(help_text='Картинка', upload_to='card/')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='filling',
            name='image',
            field=models.ImageField(help_text='Картинка', upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='card',
            field=models.ForeignKey(blank=True, help_text='Карточка товара', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='cards.card'),
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
