# Generated by Django 4.1.7 on 2023-03-25 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=1, help_text='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filling',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(help_text='Цена'),
        ),
        migrations.AlterField(
            model_name='card',
            name='filling',
            field=models.ForeignKey(help_text='Наполнение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.filling'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Наименование', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='pynata_type',
            field=models.CharField(choices=[('Circle', 'Круглая'), ('Shield', 'Щит'), ('Figure', 'Фигурная')], help_text='Форма', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='size_type',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], help_text='Размер', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='cost',
            field=models.IntegerField(help_text='Цена'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='name',
            field=models.CharField(help_text='Наименование', max_length=50),
        ),
        migrations.AlterField(
            model_name='filling',
            name='size_type',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], help_text='Тип наполнения', max_length=50),
        ),
        migrations.AlterField(
            model_name='filling',
            name='weigth',
            field=models.IntegerField(help_text='Вес в гр.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(help_text='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Наименование', max_length=50),
        ),
    ]
