# Generated by Django 4.1.7 on 2023-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_description_filling_description_alter_card_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='size_type',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('Xl', 'XL')], help_text='Размер', max_length=50),
        ),
        migrations.AlterField(
            model_name='filling',
            name='size_type',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('Xl', 'XL')], help_text='Тип наполнения', max_length=50),
        ),
    ]
